/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
package peminjaman;

import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.spi.DirStateFactory.Result;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;

class masuk{

    private Component rootPane;

    masuk(String nama, String id, String email1, String alamat1, String passwordA, String passwordB) {
        try {
            Connection kon = DriverManager.getConnection("jdbc:mysql://localhost/perpustakaan","root","");
            PreparedStatement pat=kon.prepareStatement("insert into anggota values"+"('"+id+"','"+nama+"','"+email1+"','"+alamat1+"','"+passwordA+"')");
            
            if(passwordA.equals(passwordB)){
                pat.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Anda Berhasil Mendaftar");
                Login ha = new Login();
                ha.setVisible(true);
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "Check Password Kamu Tidak Sinkron");
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Maaf ID Sudah Digunakan");
        }
    }

    
}

public class Daftar extends javax.swing.JFrame {

    /** Creates new form Daftar */
    public Daftar() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alamat = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        btn_daftar = new javax.swing.JButton();
        btn_login = new javax.swing.JButton();
        id_anggota = new javax.swing.JTextField();
        password1 = new javax.swing.JPasswordField();
        password2 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        alamat.setBackground(new java.awt.Color(236, 236, 236));
        alamat.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        alamat.setBorder(null);
        getContentPane().add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, 420, 60));

        username.setBackground(new java.awt.Color(236, 236, 236));
        username.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        username.setBorder(null);
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 430, 60));

        email.setBackground(new java.awt.Color(236, 236, 236));
        email.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        email.setBorder(null);
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 650, 420, 50));

        btn_daftar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_daftar.setForeground(new java.awt.Color(255, 255, 255));
        btn_daftar.setText("DAFTAR ");
        btn_daftar.setBorder(null);
        btn_daftar.setContentAreaFilled(false);
        btn_daftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_daftarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_daftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 780, 250, 50));

        btn_login.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_login.setText("LOGIN");
        btn_login.setBorder(null);
        btn_login.setContentAreaFilled(false);
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 850, 230, 50));

        id_anggota.setBackground(new java.awt.Color(236, 236, 236));
        id_anggota.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        id_anggota.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        id_anggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_anggotaActionPerformed(evt);
            }
        });
        getContentPane().add(id_anggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, 430, 50));

        password1.setBackground(new java.awt.Color(236, 236, 236));
        password1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        password1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 526, 420, 60));

        password2.setBackground(new java.awt.Color(236, 236, 236));
        password2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        password2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(password2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 650, 410, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/daftar.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
   // TODO add your handling code here:
        Login ha = new Login();
        ha.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_loginActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void id_anggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_anggotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_anggotaActionPerformed

    private void btn_daftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_daftarActionPerformed
        // TODO add your handling code here:
        String nama=username.getText();
        String id=id_anggota.getText();
        String email1=email.getText();
        String alamat1=alamat.getText();
        String passwordA=password1.getText();
        String passwordB=password2.getText();
        masuk masuk1 = new masuk(nama,id,email1,alamat1,passwordA,passwordB);
        this.dispose();
        
    }//GEN-LAST:event_btn_daftarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Daftar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JButton btn_daftar;
    private javax.swing.JButton btn_login;
    private javax.swing.JTextField email;
    private javax.swing.JTextField id_anggota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField password1;
    private javax.swing.JPasswordField password2;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

}
