/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peminjaman;

import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

class tambahwaktu{

    private Component rootPane;

    tambahwaktu(String id, String peminjaman1, String pengembalian) {
        try {
            Connection kon = DriverManager.getConnection("jdbc:mysql://localhost/perpustakaan","root","");
            kon.createStatement().executeUpdate("update peminjaman set tanggal_pinjam='"+peminjaman1+"',tanggal_kembali='"+pengembalian+"' where id_anggota='"+id+"'");
            JOptionPane.showMessageDialog(rootPane, "Penambahan Waktu Berhasil");
            
                daftar_peminjam pil = new daftar_peminjam();
                pil.setVisible(true);
                
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan");
        }
    }
    
}

public class daftar_peminjam extends javax.swing.JFrame {
    DefaultTableModel model;
    /**
     * Creates new form daftar_peminjam
     */
    public daftar_peminjam() {
        initComponents();
        String []judul={"ID ANGGOTA","ID BUKU","NAMA BUKU","TAHUN TERBIT","PENERBIT","TANGGAL PEMINJAMAN","TANGGAL PENGEMBALIAN"};
        model = new DefaultTableModel(judul,0);
        tabel_peminjam.setModel(model);
        tampilkan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_peminjam = new javax.swing.JTable();
        tglpeminjaman = new javax.swing.JTextField();
        tglpengembalian = new javax.swing.JTextField();
        btn_tambahtgl = new javax.swing.JButton();
        btn_kembali = new javax.swing.JButton();
        btn_kembalihlmn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        id_anggota = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(236, 236, 236));

        tabel_peminjam.setBackground(new java.awt.Color(236, 236, 236));
        tabel_peminjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        tabel_peminjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_peminjamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_peminjam);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 210, 1040, 280));

        tglpeminjaman.setBackground(new java.awt.Color(236, 236, 236));
        tglpeminjaman.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        tglpeminjaman.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(tglpeminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 590, 240, 50));

        tglpengembalian.setBackground(new java.awt.Color(236, 236, 236));
        tglpengembalian.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        tglpengembalian.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(tglpengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 590, 230, 50));

        btn_tambahtgl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_tambahtgl.setForeground(new java.awt.Color(255, 102, 51));
        btn_tambahtgl.setText("TAMBAH TANGGAL PEMINJAM");
        btn_tambahtgl.setBorder(null);
        btn_tambahtgl.setContentAreaFilled(false);
        btn_tambahtgl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahtglActionPerformed(evt);
            }
        });
        getContentPane().add(btn_tambahtgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 720, 310, 40));

        btn_kembali.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btn_kembali.setForeground(new java.awt.Color(255, 102, 255));
        btn_kembali.setText("KEMBALIKAN BUKU");
        btn_kembali.setBorder(null);
        btn_kembali.setContentAreaFilled(false);
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btn_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 720, 240, 40));

        btn_kembalihlmn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_kembalihlmn.setForeground(new java.awt.Color(102, 0, 51));
        btn_kembalihlmn.setText("KEMBALI");
        btn_kembalihlmn.setBorder(null);
        btn_kembalihlmn.setContentAreaFilled(false);
        btn_kembalihlmn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembalihlmnActionPerformed(evt);
            }
        });
        getContentPane().add(btn_kembalihlmn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 720, 180, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/peminjam.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 900));

        id_anggota.setForeground(new java.awt.Color(255, 255, 255));
        id_anggota.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        id_anggota.setCaretColor(new java.awt.Color(255, 255, 255));
        id_anggota.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(id_anggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 590, 160, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahtglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahtglActionPerformed
        // TODO add your handling code here:
         String id=id_anggota.getText();
        String peminjaman1=tglpeminjaman.getText();
        String pengembalian=tglpengembalian.getText();
        tambahwaktu tambah2 = new tambahwaktu(id,peminjaman1,pengembalian);
        this.dispose();
    }//GEN-LAST:event_btn_tambahtglActionPerformed

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        // TODO add your handling code here:
        try {
            Connection kon = DriverManager.getConnection("jdbc:mysql://localhost/perpustakaan","root","");
            kon.createStatement().executeUpdate("delete from peminjaman where id_anggota='"+id_anggota.getText()+"'");
            JOptionPane.showMessageDialog(rootPane, "Buku Telah Dikembalikan");
            
                daftar_peminjam pil = new daftar_peminjam();
                pil.setVisible(true);
                this.dispose();
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan");
        }
    }//GEN-LAST:event_btn_kembaliActionPerformed

    private void btn_kembalihlmnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembalihlmnActionPerformed
        // TODO add your handling code here:
        peminjamanbuku pil = new peminjamanbuku();
                pil.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_btn_kembalihlmnActionPerformed

    private void tabel_peminjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_peminjamMouseClicked
        // TODO add your handling code here:
        int i = tabel_peminjam.getSelectedRow();
        if(i>-1){
            id_anggota.setText(model.getValueAt(i, 0).toString());
            tglpeminjaman.setText(model.getValueAt(i, 5).toString());
            tglpengembalian.setText(model.getValueAt(i, 6).toString());
        }
    }//GEN-LAST:event_tabel_peminjamMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(daftar_peminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(daftar_peminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(daftar_peminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(daftar_peminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new daftar_peminjam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_kembalihlmn;
    private javax.swing.JButton btn_tambahtgl;
    private javax.swing.JTextField id_anggota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_peminjam;
    private javax.swing.JTextField tglpeminjaman;
    private javax.swing.JTextField tglpengembalian;
    // End of variables declaration//GEN-END:variables

    private void tampilkan() {
        int row = tabel_peminjam.getRowCount();
        for(int a=0; a<row; a++){
            model.removeRow(0);
        }
        try {
            //To change body of generated methods, choose Tools | Templates.
            Connection as = DriverManager.getConnection("jdbc:mysql://localhost/perpustakaan","root","");
            ResultSet rs= as.createStatement().executeQuery("SELECT * FROM peminjaman");
            while(rs.next()){
                String data[] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7)};
                model.addRow(data);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Gagal Menyambungkan Database");
        }
    }
}
