/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peminjaman;

import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


class input{

    private Component rootPane;

    input(String idanggota, String idbuku, String nama_buku, String tahun_terbit, String penerbit1, String tglpeminjaman1, String tglpengembalian1) {
        try {
            Connection kon = DriverManager.getConnection("jdbc:mysql://localhost/perpustakaan","root","");
            kon.createStatement().executeUpdate("insert into peminjaman values"+"('"+idanggota+"','"+idbuku+"','"+nama_buku+"','"+tahun_terbit+"','"+penerbit1+"','"+tglpeminjaman1+"','"+tglpengembalian1+"')");
            JOptionPane.showMessageDialog(rootPane, "Anda Berhasil Meminjam");
            
                daftar_peminjam pil = new daftar_peminjam();
                pil.setVisible(true);
            
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Id Anggota Sudah Meminjam");
        }
    }

    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

  
    
}

public class peminjamanbuku extends javax.swing.JFrame {
    DefaultTableModel model;
    /**
     * Creates new form peminjamanbuku
     */
     String u = Register.getid();
    public peminjamanbuku() {
        initComponents();
        id_anggota.setText(u);
        String []judul={"ID BUKU","NAMA BUKU","TAHUN TERBIT","PENERBIT"};
        model = new DefaultTableModel(judul,0);
        tabel_buku.setModel(model);
        tampilkan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tglpeminjaman = new javax.swing.JTextField();
        id_buku = new javax.swing.JTextField();
        namabuku = new javax.swing.JTextField();
        tahunterbit = new javax.swing.JTextField();
        penerbit = new javax.swing.JTextField();
        tglpengembalian = new javax.swing.JTextField();
        pinjam = new javax.swing.JButton();
        dftr_pinjam = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_buku = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        id_anggota = new javax.swing.JPasswordField();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tglpeminjaman.setBackground(new java.awt.Color(236, 236, 236));
        tglpeminjaman.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tglpeminjaman.setBorder(null);
        tglpeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglpeminjamanActionPerformed(evt);
            }
        });
        getContentPane().add(tglpeminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, 350, 40));

        id_buku.setBackground(new java.awt.Color(236, 236, 236));
        id_buku.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        id_buku.setBorder(null);
        id_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_bukuActionPerformed(evt);
            }
        });
        getContentPane().add(id_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 350, 40));

        namabuku.setBackground(new java.awt.Color(236, 236, 236));
        namabuku.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        namabuku.setBorder(null);
        namabuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namabukuActionPerformed(evt);
            }
        });
        getContentPane().add(namabuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 350, 40));

        tahunterbit.setBackground(new java.awt.Color(236, 236, 236));
        tahunterbit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tahunterbit.setBorder(null);
        tahunterbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahunterbitActionPerformed(evt);
            }
        });
        getContentPane().add(tahunterbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 580, 350, 40));

        penerbit.setBackground(new java.awt.Color(236, 236, 236));
        penerbit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        penerbit.setBorder(null);
        penerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penerbitActionPerformed(evt);
            }
        });
        getContentPane().add(penerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 690, 350, 40));

        tglpengembalian.setBackground(new java.awt.Color(236, 236, 236));
        tglpengembalian.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tglpengembalian.setBorder(null);
        tglpengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglpengembalianActionPerformed(evt);
            }
        });
        getContentPane().add(tglpengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 470, 350, 40));

        pinjam.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        pinjam.setForeground(new java.awt.Color(51, 51, 255));
        pinjam.setText("Pinjam");
        pinjam.setBorder(null);
        pinjam.setContentAreaFilled(false);
        pinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinjamActionPerformed(evt);
            }
        });
        getContentPane().add(pinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 820, 150, 30));

        dftr_pinjam.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        dftr_pinjam.setForeground(new java.awt.Color(102, 0, 51));
        dftr_pinjam.setText("Daftar Peminjam");
        dftr_pinjam.setBorder(null);
        dftr_pinjam.setContentAreaFilled(false);
        dftr_pinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dftr_pinjamActionPerformed(evt);
            }
        });
        getContentPane().add(dftr_pinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 820, 160, 30));

        logout.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 102, 102));
        logout.setText("LOGOUT");
        logout.setBorder(null);
        logout.setContentAreaFilled(false);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 810, 140, 50));

        tabel_buku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_bukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_buku);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 550, 630, 270));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/input.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 900));

        id_anggota.setBackground(new java.awt.Color(236, 236, 236));
        id_anggota.setForeground(new java.awt.Color(255, 255, 255));
        id_anggota.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        id_anggota.setCaretColor(new java.awt.Color(255, 255, 255));
        id_anggota.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(id_anggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 360, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tglpeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglpeminjamanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglpeminjamanActionPerformed

    private void id_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_bukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_bukuActionPerformed

    private void namabukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namabukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namabukuActionPerformed

    private void tahunterbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahunterbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tahunterbitActionPerformed

    private void penerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_penerbitActionPerformed

    private void tglpengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglpengembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglpengembalianActionPerformed

    private void pinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinjamActionPerformed
        // TODO add your handling code here:
        String idanggota=id_anggota.getText();
        String idbuku=id_buku.getText();
        String nama_buku=namabuku.getText();
        String tahun_terbit=tahunterbit.getText();
        String penerbit1=penerbit.getText();
        String tglpeminjaman1=tglpeminjaman.getText();
        String tglpengembalian1=tglpengembalian.getText();
        input inputkan = new input (idanggota,idbuku,nama_buku,tahun_terbit,penerbit1,tglpeminjaman1,tglpengembalian1);
        this.dispose();
    }//GEN-LAST:event_pinjamActionPerformed

    private void dftr_pinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dftr_pinjamActionPerformed
        // TODO add your handling code here:
                daftar_peminjam pil = new daftar_peminjam();
                pil.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_dftr_pinjamActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        Login ha = new Login();
        ha.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void tabel_bukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_bukuMouseClicked
        // TODO add your handling code here:
        int i = tabel_buku.getSelectedRow();
        if(i>-1){
            id_buku.setText(model.getValueAt(i, 0).toString());
            namabuku.setText(model.getValueAt(i, 1).toString());
            tahunterbit.setText(model.getValueAt(i, 2).toString());
            penerbit.setText(model.getValueAt(i, 3).toString());
        }
    }//GEN-LAST:event_tabel_bukuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(peminjamanbuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(peminjamanbuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(peminjamanbuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(peminjamanbuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new peminjamanbuku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dftr_pinjam;
    private javax.swing.JPasswordField id_anggota;
    private javax.swing.JTextField id_buku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logout;
    private javax.swing.JTextField namabuku;
    private javax.swing.JTextField penerbit;
    private javax.swing.JButton pinjam;
    private javax.swing.JTable tabel_buku;
    private javax.swing.JTextField tahunterbit;
    private javax.swing.JTextField tglpeminjaman;
    private javax.swing.JTextField tglpengembalian;
    // End of variables declaration//GEN-END:variables

    private void tampilkan() {
       int row = tabel_buku.getRowCount();
        for(int a=0; a<row; a++){
            model.removeRow(0);
        }
        try {
            //To change body of generated methods, choose Tools | Templates.
            Connection as = DriverManager.getConnection("jdbc:mysql://localhost/perpustakaan","root","");
            ResultSet rs= as.createStatement().executeQuery("SELECT * FROM buku");
            while(rs.next()){
                String data[] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)};
                model.addRow(data);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Gagal Menyambungkan Database");
        }
    }
}
